# Generated by Django 3.2.6 on 2021-08-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollAnswer',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='PollQuestion',
            new_name='Survey',
        ),
    ]
